{
    "name": "Anuncios Lumicolor",
    "summary": """
    Instance creator for anuncioslumicolor. This is the app.
    """,
    "author": "Vauxoo",
    "website": "https://www.vauxoo.com",
    "license": "LGPL-3",
    "category": "Installer",
    "version": "16.0.1.0.1",
    "depends": [
        "account_payment",
        "board",
        "crm_iap_mine",
        "crm_iap_enrich",
        "helpdesk_repair",
        "hr_expense",
        "hr_timesheet",
        "l10n_mx_cash_basis_entries",
        "l10n_mx_edi_40",
        "l10n_mx_edi_cancellation",
        "l10n_mx_edi_document",
        "l10n_mx_edi_payslip",
        "mrp_workorder",
        "purchase",
        "sale_product_configurator",
        "social_media",
    ],
    "data": [
        "security/ir_module_category_security.xml",
        "security/ir.model.access.csv",
        "security/res_groups_security.xml",
        "data/res_company_data.xml",
        "views/crm_lead_views.xml",
        "views/crm_stage_views.xml",
        "views/mrp_production_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "reports/report_external_layouts.xml",
        "reports/report_picking.xml",
        "reports/report_saleorder_document.xml",
    ],
    "demo": [
        "demo/res_partner_demo.xml",
    ],
    "assets": {
        "web.report_assets_common": [
            "anuncioslumicolor/static/src/scss/fonts.scss",
            "anuncioslumicolor/static/src/scss/report.scss",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": True,
}
